using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using oculus_sport.Models;
using oculus_sport.Services.Storage;
using oculus_sport.ViewModels.Base;

namespace oculus_sport.ViewModels.Main
{
    [QueryProperty(nameof(CurrentUser), "User")]
    public partial class HomePageViewModel : BaseViewModel
    {
        // --- sync with login & firestore
        private readonly FirebaseDataService _firebaseService;
        [ObservableProperty]
        private User currentUser;

        // This partial method is auto‑generated by the toolkit
        partial void OnCurrentUserChanged(User value)
        {
            if (value != null)
                UserName = value.Name;
        }

        [ObservableProperty]
        private string userName;


        [ObservableProperty]
        private ObservableCollection<SportCategory> _categories = new();

        [ObservableProperty]
        private ObservableCollection<Facility> _facilities = new();

        private List<Facility> _allFacilities = new();

        public HomePageViewModel(FirebaseDataService firebaseService)
        {
            _firebaseService = firebaseService;
            Title = "Home";
            LoadData();
        }


        // --------- sycn homepage user name
        public async Task UserHomepageSync(string uid, string idToken)
        {
            var user = await _firebaseService.GetUserFromFirestore(uid, idToken);
            if (user != null)
            {
                CurrentUser = user;
            }
        }


        private void LoadData()
        {
            Categories.Add(new SportCategory { Name = "Badminton", IsSelected = true });
            Categories.Add(new SportCategory { Name = "Ping-Pong" });
            Categories.Add(new SportCategory { Name = "Basketball" });

            _allFacilities.Clear();
            for (int i = 1; i <= 3; i++)
                _allFacilities.Add(new Facility { Name = $"Badminton Court {i}", Location = "UTS Indoor Hall", Price = "Free", Rating = 4.5, ImageUrl = "court_badminton.png" });

            for (int i = 1; i <= 4; i++)
                _allFacilities.Add(new Facility { Name = $"Ping-Pong Table {i}", Location = "Student Center L2", Price = "Free", Rating = 4.8, ImageUrl = "court_pingpong.png" });

            _allFacilities.Add(new Facility { Name = "Basketball Court 1", Location = "Outdoor Complex", Price = "Free", Rating = 4.2, ImageUrl = "court_basketball.png" });

            FilterFacilities("Badminton");
        }

        [RelayCommand]
        void SelectCategory(SportCategory category)
        {
            if (Categories == null) return;
            foreach (var c in Categories) c.IsSelected = false;
            category.IsSelected = true;
            FilterFacilities(category.Name);
        }

        private void FilterFacilities(string categoryName)
        {
            Facilities.Clear();
            var filtered = _allFacilities.Where(f => f.Name.Contains(categoryName, StringComparison.OrdinalIgnoreCase));
            foreach (var facility in filtered) Facilities.Add(facility);
        }

        [RelayCommand]
        async Task BookFacility(Facility facility)
        {
            var navigationParameter = new Dictionary<string, object> { { "Facility", facility } };
            await Shell.Current.GoToAsync("BookingPage", navigationParameter);
        }

        [RelayCommand]
        async Task GoToNotifications()
        {
            await Shell.Current.GoToAsync("NotificationPage");
        }
    }
}